apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dailytasks.example.com
spec:
  group: example.com
  names:
    kind: DailyTask
    listKind: DailyTaskList
    plural: dailytasks
    singular: dailytask
    shortNames:
    - dt
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            required:
            - taskName
            properties:
              taskName:
                type: string
                description: The name of the task
              description:
                type: string
                description: The description of the task
              priority:
                type: integer
                description: The priority of the task
                minimum: 1
                maximum: 5
          status:
            type: object
            # x-kubernetes-preserve-unknown-fields must be at this level, not under subresources
            x-kubernetes-preserve-unknown-fields: true
    subresources:
      status: {}